// Package autoconfig deterministically generates an `.agnt.kdl` for a detected
// project, so simple projects (a package.json web app, a dotnet site, a Go or
// Python repo) are configured with zero LLM involvement. Only projects this
// package cannot confidently configure fall back to the LLM-driven setup flow.
//
// The generated config wires the obvious things: the dev server as an
// autostart script with a reverse proxy in front of it, and lint/test as
// on-demand scripts that surface in the overlay queue. The file is plain KDL
// the developer can edit; piece D's live reconcile applies edits without a
// restart.
package autoconfig

import (
	"fmt"
	"strings"

	"github.com/standardbeagle/agnt/internal/project"
)

// Generate builds `.agnt.kdl` text for p and reports whether it was confident
// enough to do so. It returns ok=false for an unknown project type or one with
// no useful commands — those fall back to the LLM setup flow.
func Generate(p *project.Project) (string, bool) {
	if p == nil || p.Type == project.ProjectUnknown {
		return "", false
	}

	server := serverCommand(p)
	test := project.GetCommandByName(p, "test")
	lint := project.GetCommandByName(p, "lint")
	build := project.GetCommandByName(p, "build")

	// Need at least one actionable thing to be worth generating a config.
	if server == nil && test == nil && lint == nil {
		return "", false
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by agnt for this %s project (%q). Edit freely —\n", p.Type, p.Name)
	b.WriteString("// changes are applied live (no restart). Add scripts/proxies as needed.\n\n")

	b.WriteString("scripts {\n")
	if server != nil {
		writeScript(&b, "dev", shellString(server), true)
	}
	// Non-server scripts are registered but not autostarted — they show up in
	// the overlay as on-demand actions (lint/test/build checkboxes).
	if test != nil {
		writeScript(&b, "test", shellString(test), false)
	}
	if lint != nil {
		writeScript(&b, "lint", shellString(lint), false)
	}
	if build != nil {
		writeScript(&b, "build", shellString(build), false)
	}
	b.WriteString("}\n")

	// A reverse proxy in front of the dev server, linked to the dev script so
	// it is created when the script reports its URL.
	if server != nil {
		b.WriteString("\nproxies {\n")
		b.WriteString("    dev {\n")
		b.WriteString("        script \"dev\"\n")
		b.WriteString("    }\n")
		b.WriteString("}\n")
	}

	return b.String(), true
}

// serverCommand returns the long-running dev-server command worth proxying, or
// nil when the project has no obvious server. It is deliberately conservative:
// a plain `go run .` or a Python entry point is not assumed to be a server.
func serverCommand(p *project.Project) *project.CommandDef {
	switch p.Type {
	case project.ProjectNode:
		// Only when package.json actually declares the script.
		if hasNodeScript(p, "dev") {
			return project.GetCommandByName(p, "dev")
		}
		if hasNodeScript(p, "start") {
			return project.GetCommandByName(p, "start")
		}
		return nil
	case project.ProjectDotnet:
		return project.GetCommandByName(p, "dev")
	case project.ProjectGo:
		// Wails desktop apps serve a frontend via `wails dev`; plain Go does not.
		if p.Metadata["framework"] == "wails" {
			return project.GetCommandByName(p, "dev")
		}
		return nil
	default:
		return nil
	}
}

// hasNodeScript reports whether package.json declared the named npm script
// (project.Detect records them as a comma-separated list in Metadata).
func hasNodeScript(p *project.Project, name string) bool {
	for _, s := range strings.Split(p.Metadata["scripts"], ",") {
		if strings.TrimSpace(s) == name {
			return true
		}
	}
	return false
}

// shellString renders a CommandDef as a single shell command string suitable
// for the `run` field, e.g. "npm run dev" or "go test -v ./...".
func shellString(c *project.CommandDef) string {
	if len(c.Args) == 0 {
		return c.Command
	}
	return c.Command + " " + strings.Join(c.Args, " ")
}

// writeScript emits one `name { run "..."; autostart bool }` block.
func writeScript(b *strings.Builder, name, run string, autostart bool) {
	fmt.Fprintf(b, "    %s {\n", name)
	fmt.Fprintf(b, "        run %q\n", run)
	if autostart {
		b.WriteString("        autostart true\n")
	}
	b.WriteString("    }\n")
}
