// Package autoconfig deterministically generates an `.agnt.kdl` for a detected
// project, so simple projects (a package.json web app, a dotnet site, a Go or
// Python repo) are configured with zero LLM involvement. Only projects this
// package cannot confidently configure fall back to the LLM-driven setup flow.
//
// The generated config wires the obvious things: the dev server as an
// autostart script with a reverse proxy in front of it, and lint/test as
// on-demand scripts that surface in the overlay queue. The file is plain KDL
// the developer can edit; piece D's live reconcile applies edits without a
// restart.
package autoconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/standardbeagle/agnt/internal/project"
)

// Generate builds `.agnt.kdl` text for p and reports whether it was confident
// enough to do so. It returns ok=false for an unknown project type or one with
// no useful commands — those fall back to the LLM setup flow.
func Generate(p *project.Project) (string, bool) {
	if p == nil {
		return "", false
	}
	if isRootStaticSite(p) {
		return generateStaticSiteConfig(p), true
	}

	// Servers come from the detectors/augmenters (framework defaults,
	// compose, Procfile, nested apps); the legacy per-type guess fills in
	// only when they found nothing.
	servers := p.Servers
	if len(servers) == 0 && len(p.Proxies) == 0 {
		if legacy := serverCommand(p); legacy != nil {
			servers = []project.Server{{Name: "dev", Run: shellString(legacy), Proxy: true}}
		}
	}
	if p.Type == project.ProjectUnknown && len(servers) == 0 && len(p.Proxies) == 0 {
		return "", false
	}

	test := project.GetCommandByName(p, "test")
	lint := project.GetCommandByName(p, "lint")
	build := project.GetCommandByName(p, "build")

	// Need at least one actionable thing to be worth generating a config.
	if len(servers) == 0 && len(p.Proxies) == 0 && test == nil && lint == nil {
		return "", false
	}

	taken := make(map[string]bool, len(servers))
	for _, s := range servers {
		taken[s.Name] = true
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by agnt for this %s project (%q). Edit freely —\n", p.Type, p.Name)
	b.WriteString("// changes are applied live (no restart). Add scripts/proxies as needed.\n\n")

	b.WriteString("scripts {\n")
	manualNoted := false
	for _, s := range servers {
		if s.Manual && !manualNoted {
			writeManualNote(&b, p)
			manualNoted = true
		}
		writeServerScript(&b, s)
	}
	// Non-server scripts are registered but not autostarted — they show up in
	// the overlay as on-demand actions (lint/test/build checkboxes). A server
	// that already took the name (a Procfile "test" entry) keeps it.
	if test != nil && !taken["test"] {
		writeScript(&b, "test", shellString(test), false)
	}
	if lint != nil && !taken["lint"] {
		writeScript(&b, "lint", shellString(lint), false)
	}
	if build != nil && !taken["build"] {
		writeScript(&b, "build", shellString(build), false)
	}
	b.WriteString("}\n")

	// Reverse proxies: one per server that serves HTTP, linked to its script
	// so it is created when the script reports its URL, with the known port
	// as fallback so it exists even when the output prints no URL; plus one
	// per fixed-port target (compose services).
	var proxies strings.Builder
	for _, s := range servers {
		if !s.Proxy {
			continue
		}
		fmt.Fprintf(&proxies, "    %s {\n        script %q\n", s.Name, s.Name)
		if s.Port > 0 {
			fmt.Fprintf(&proxies, "        fallback-port %d\n", s.Port)
		}
		proxies.WriteString("    }\n")
	}
	for _, px := range p.Proxies {
		name := px.Name
		if taken[name] {
			name += "-proxy"
		}
		fmt.Fprintf(&proxies, "    %s {\n        port %d\n    }\n", name, px.Port)
	}
	if proxies.Len() > 0 {
		b.WriteString("\nproxies {\n")
		b.WriteString(proxies.String())
		b.WriteString("}\n")
	}

	return b.String(), true
}

// writeServerScript emits a script block for a detected server, with its
// working directory and known port when present. A Manual server is written
// without autostart: it is ready to run, and the developer turns it on.
func writeServerScript(b *strings.Builder, s project.Server) {
	fmt.Fprintf(b, "    %s {\n", s.Name)
	fmt.Fprintf(b, "        run %q\n", s.Run)
	if s.Cwd != "" {
		fmt.Fprintf(b, "        cwd %q\n", s.Cwd)
	}
	if s.Port > 0 {
		fmt.Fprintf(b, "        ports %d\n", s.Port)
	}
	if !s.Manual {
		b.WriteString("        autostart true\n")
	}
	b.WriteString("    }\n")
}

// writeManualNote explains, in the file itself, why the per-app servers that
// follow do not autostart. Without it the config reads as if agnt failed to
// configure them.
func writeManualNote(b *strings.Builder, p *project.Project) {
	owner := "another script"
	if f := p.Metadata["compose"]; f != "" {
		owner = f
	} else if f := p.Metadata["procfile"]; f != "" {
		owner = f
	}
	b.WriteString("    // Below: the apps in this repository, ready to run but not\n")
	fmt.Fprintf(b, "    // autostarted, because %s already serves their ports.\n", owner)
	b.WriteString("    // Stop that service, then set autostart true here to develop\n")
	b.WriteString("    // against the local process instead.\n")
}

// isRootStaticSite recognizes the deliberately narrow zero-build case: an
// otherwise unrecognized project with an index.html at its root. Known project
// markers take precedence in project.Detect, and callers invoke Generate only
// when no .agnt.kdl already exists, so this cannot replace an explicit setup.
func isRootStaticSite(p *project.Project) bool {
	if p.Type != project.ProjectUnknown || p.Path == "" {
		return false
	}
	info, err := os.Stat(filepath.Join(p.Path, "index.html"))
	return err == nil && !info.IsDir()
}

// generateStaticSiteConfig serves a root index.html with Python's standard
// library server. The command prints its URL only after binding so the
// script-linked proxy is created immediately rather than waiting for fallback.
func generateStaticSiteConfig(p *project.Project) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by agnt for static site %q. Edit freely —\n", p.Name)
	b.WriteString("// changes are applied live (no restart).\n\n")
	b.WriteString("scripts {\n")
	writeScript(&b, "dev", `python3 -u -c "from http.server import ThreadingHTTPServer,SimpleHTTPRequestHandler as H;s=ThreadingHTTPServer(('0.0.0.0',8000),H);print('http://localhost:8000',flush=True);s.serve_forever()"`, true)
	b.WriteString("}\n\nproxies {\n    dev {\n        script \"dev\"\n        fallback-port 8000\n    }\n}\n")
	return b.String()
}

// serverCommand returns the long-running dev-server command worth proxying, or
// nil when the project has no obvious server. It is deliberately conservative:
// a plain `go run .` or a Python entry point is not assumed to be a server.
func serverCommand(p *project.Project) *project.CommandDef {
	switch p.Type {
	case project.ProjectNode:
		// Only when package.json actually declares the script.
		if hasNodeScript(p, "dev") {
			return project.GetCommandByName(p, "dev")
		}
		if hasNodeScript(p, "start") {
			return project.GetCommandByName(p, "start")
		}
		return nil
	case project.ProjectDotnet:
		// `dotnet watch run` needs a project file in the cwd; at a
		// solution-only root it fails with "couldn't find a project to run".
		// Emitting it anyway would autostart a script we know cannot work.
		if p.Metadata["project"] == "" {
			return nil
		}
		return project.GetCommandByName(p, "dev")
	case project.ProjectGo:
		// Wails desktop apps serve a frontend via `wails dev`; plain Go does not.
		if p.Metadata["framework"] == "wails" {
			return project.GetCommandByName(p, "dev")
		}
		return nil
	default:
		return nil
	}
}

// hasNodeScript reports whether package.json declared the named npm script
// (project.Detect records them as a comma-separated list in Metadata).
func hasNodeScript(p *project.Project, name string) bool {
	for _, s := range strings.Split(p.Metadata["scripts"], ",") {
		if strings.TrimSpace(s) == name {
			return true
		}
	}
	return false
}

// shellString renders a CommandDef as a single shell command string suitable
// for the `run` field, e.g. "npm run dev" or "go test -v ./...".
func shellString(c *project.CommandDef) string {
	if len(c.Args) == 0 {
		return c.Command
	}
	return c.Command + " " + strings.Join(c.Args, " ")
}

// writeScript emits one `name { run "..."; autostart bool }` block.
func writeScript(b *strings.Builder, name, run string, autostart bool) {
	fmt.Fprintf(b, "    %s {\n", name)
	fmt.Fprintf(b, "        run %q\n", run)
	if autostart {
		b.WriteString("        autostart true\n")
	}
	b.WriteString("    }\n")
}
