// Package scripts provides embedded JavaScript for the DevTool proxy instrumentation.
package scripts

import (
	_ "embed"
	"strings"
	"sync"
)

// Individual script files embedded at compile time
var (
	//go:embed core.js
	coreJS string

	//go:embed frames.js
	framesJS string

	//go:embed authbreakout.js
	authBreakoutJS string

	//go:embed ui-tokens.js
	uiTokensJS string

	//go:embed shadow-root.js
	shadowRootJS string

	//go:embed utils.js
	utilsJS string

	//go:embed overlay.js
	overlayJS string

	//go:embed inspection.js
	inspectionJS string

	//go:embed tree.js
	treeJS string

	//go:embed visual.js
	visualJS string

	//go:embed layout.js
	layoutJS string

	//go:embed interactive.js
	interactiveJS string

	//go:embed capture.js
	captureJS string

	//go:embed accessibility.js
	accessibilityJS string

	//go:embed audit-utils.js
	auditUtilsJS string

	//go:embed audit-report.js
	auditReportJS string

	//go:embed audit-dom.js
	auditDomJS string

	//go:embed audit-css.js
	auditCssJS string

	//go:embed audit-security.js
	auditSecurityJS string

	//go:embed audit-performance.js
	auditPerformanceJS string

	//go:embed audit-quality.js
	auditQualityJS string

	//go:embed audit-api.js
	auditApiJS string

	//go:embed audit-loading.js
	auditLoadingJS string

	//go:embed interaction.js
	interactionJS string

	//go:embed framework-detector.js
	frameworkDetectorJS string

	//go:embed api-tracker.js
	apiTrackerJS string

	//go:embed mutation.js
	mutationJS string

	//go:embed toast.js
	toastJS string

	//go:embed indicator-bridge.js
	indicatorBridgeJS string

	//go:embed walkthrough-proxy.js
	walkthroughProxyJS string

	//go:embed indicator-styles.js
	indicatorStylesJS string

	//go:embed indicator-data.js
	indicatorDataJS string

	//go:embed indicator-tabs.js
	indicatorTabsJS string

	//go:embed indicator.js
	indicatorJS string

	//go:embed sketch.js
	sketchJS string

	//go:embed design.js
	designJS string

	//go:embed walkthrough.js
	walkthroughJS string

	//go:embed variant-engine.js
	variantEngineJS string

	//go:embed walkthrough-viewer.js
	walkthroughViewerJS string

	//go:embed feedback-client.js
	feedbackClientJS string

	//go:embed public-boot.js
	publicBootJS string

	//go:embed palette.js
	paletteJS string

	//go:embed style-editor.js
	styleEditorJS string

	//go:embed override-store.js
	overrideStoreJS string

	//go:embed transform.js
	transformJS string

	//go:embed voice.js
	voiceJS string

	//go:embed snapshot-helper.js
	snapshotHelperJS string

	//go:embed diagnostics.js
	diagnosticsJS string

	//go:embed session.js
	sessionJS string

	//go:embed store.js
	storeJS string

	//go:embed content.js
	contentJS string

	//go:embed text-fragility.js
	textFragilityJS string

	//go:embed responsive-risk.js
	responsiveRiskJS string

	//go:embed wireframe.js
	wireframeJS string

	//go:embed responsive.js
	responsiveJS string

	//go:embed responsive-mode.js
	responsiveModeJS string

	//go:embed api.js
	apiJS string

	//go:embed html2canvas-loader.js
	html2canvasLoaderJS string

	//go:embed html2canvas-pro.min.js
	html2canvasProJS string

	//go:embed axe-core.min.js
	axeCoreJS string
)

// Role identifies which per-frame bundle flavour to build. The proxy knows
// the frame role at injection time: the chrome-shell document is generated by
// BuildShellDocument (chrome), a wrapped content frame's request carries the
// frame marker (content), and everything else — unwrapped fallback, HTML
// fragments, passive embeds, legacy injection — gets the full bundle, which
// is byte-for-byte today's behaviour.
type Role string

const (
	// RoleFull is the complete bundle: every module (passive/legacy default).
	RoleFull Role = ""
	// RoleChrome is the shell bundle: shared + chrome-only modules, without
	// the content-only set.
	RoleChrome Role = "chrome"
	// RoleContent is the content-frame bundle: shared modules (including the
	// indicator-bridge / walkthrough-proxy forwarding stubs) + content-only
	// modules, without the chrome-only set.
	RoleContent Role = "content"
	// RolePublic is the HARD-ALLOWLISTED public bundle for the walkthrough-publish
	// plane (P4). Unlike RoleChrome/RoleContent — which are SUBTRACTIVE filters
	// over the full module set — RolePublic is built from an EXPLICIT ALLOWLIST
	// (rolePublicModules) and contains ONLY those members: the variant renderer,
	// the read-only walkthrough viewer, the feedback client, and the boot glue
	// that starts the viewer from the share token in the URL. It carries NONE
	// of the dev-control surface (no core WS/exec channel, no __devtool control
	// API, no audits/capture/inspection/design/indicator/authbreakout), ships no
	// html2canvas, and runs under `script-src 'self'` with no eval/inline. The
	// dependency-closure + forbidden-symbol tests in role_public_test.go fail the
	// build if a forbidden module ever enters this bundle.
	RolePublic Role = "public"
)

// combinedScripts caches one built bundle per Role.
var combinedScripts sync.Map // Role -> string

// Version is the agnt version to inject into scripts.
// Set this before calling GetCombinedScript() for the first time.
var Version = "dev"

// moduleEntry declares a JS module and its hard dependencies.
// Dependencies must appear earlier in moduleOrder.
type moduleEntry struct {
	name string
	deps []string
}

// moduleOrder defines the load order for all embedded modules.
// Each entry names the module and lists modules it requires at load time.
// The buildCombinedScript function iterates this slice instead of a
// hardcoded sequence so that the dependency declarations are authoritative
// and verified at build time by TestModuleDependencyOrder.
var moduleOrder = []moduleEntry{
	// frames.js establishes the per-frame role (chrome|content|passive) + the
	// shell-side frame registry / active-target pointer / URL-bar nav-sync. It
	// MUST load FIRST — before core's WS/error-tracking init and before
	// interaction's listener attach — so those modules can gate their runtime on
	// window.__devtool_frame_role. It has no dependencies (creates its own
	// window.__devtool namespace defensively).
	{"frames", nil},
	// authbreakout reads window.__devtool_frame_role (set by frames) at eval
	// time and, in a popup return, must run before anything else touches the
	// window (it relays the callback URL to the opener and closes). Shared
	// role: shell exposes __devtool_auth, content intercepts navigations,
	// passive frames no-op.
	{"authbreakout", []string{"frames"}},
	{"core", nil},
	// html2canvas-loader publishes window.__devtool_ensureHtml2canvas, the
	// on-demand injector for the html2canvas-pro capture library. Dependency-free
	// (pure DOM) and inert until a capture site calls it, so it is safe anywhere;
	// it ships in every non-public bundle so both the chrome shell and content
	// frames can lazy-load html2canvas into their own window on first capture.
	{"html2canvas-loader", nil},
	// ui-tokens.js publishes window.__devtoolTokens (z-index scale, light/dark
	// color palettes, motion prefs) and the __devtoolOverlayStack Escape
	// coordinator. It MUST load before every UI module (toast, indicator,
	// palette, design, style-editor, sketch, overlay) because those build
	// their style strings from the tokens at module-eval time.
	{"ui-tokens", nil},
	// shadow-root.js MUST be loaded before any module that mounts UI so that
	// window.__devtoolGetMountRoot() is available when indicator/overlay init.
	// It has no dependencies of its own — pure DOM bootstrap.
	{"shadow-root", nil},
	{"framework-detector", nil},
	{"api-tracker", nil},
	{"utils", nil},
	{"overlay", []string{"utils", "shadow-root"}},
	{"inspection", []string{"utils"}},
	{"tree", []string{"utils"}},
	{"visual", []string{"utils"}},
	{"layout", []string{"utils", "inspection", "visual"}},
	{"interactive", []string{"utils"}},
	{"capture", []string{"utils"}},
	{"accessibility", []string{"utils"}},
	{"audit-utils", nil},
	{"audit-report", nil},
	{"audit-dom", []string{"utils"}},
	{"audit-css", []string{"utils"}},
	{"audit-security", []string{"utils", "audit-utils"}},
	{"audit-performance", []string{"utils", "audit-utils"}},
	// audit-api reads the recorded fetch/XHR buffer exposed by api-tracker, so
	// it must load after api-tracker (and utils for the shared conventions).
	{"audit-api", []string{"utils", "api-tracker"}},
	// audit-loading reads the spinner timeline exposed by mutation.js at call
	// time (window.__devtool_spinners), so there is no hard load-order
	// dependency on mutation — utils is required only for the shared
	// finding-id / grade conventions.
	{"audit-loading", []string{"utils"}},
	{"audit-quality", []string{"utils", "audit-dom", "audit-css", "audit-security", "audit-performance"}},
	{"interaction", []string{"utils", "core"}},
	{"mutation", []string{"utils", "core"}},
	{"toast", nil},
	{"voice", []string{"core"}},
	{"sketch", []string{"core", "voice"}},
	{"design", []string{"core", "utils"}},
	// walkthrough-proxy installs the non-host forwarding surface
	// (window.__devtool_walkthrough → parent host) in content/passive frames.
	// Shared role set: it ships in every bundle and self-gates on the same
	// isHost predicate as walkthrough.js, so the two never both install.
	{"walkthrough-proxy", []string{"frames"}},
	// walkthrough hosts the live-demo panel in the chrome shell and reaches the
	// active content frame via the shell frame registry. Needs core (transport)
	// + frames (role + registry); loads after design, before indicator/api.
	// Chrome-only: content frames get walkthrough-proxy instead.
	{"walkthrough", []string{"core", "frames", "walkthrough-proxy"}},
	// variant-engine is the declarative variant overlay renderer for the public
	// walkthrough-publish plane (P3). It is dependency-free (pure DOM + its own
	// isolated IIFE — it keeps a leading space after `function` so wrapModule
	// leaves its IIFE intact rather than merging it into the shared scope) and
	// inert until window.__variantEngine.create() is called, so it is safe to
	// ship in every role bundle. P4 moves it into the hard RolePublic split.
	{"variant-engine", nil},
	// walkthrough-viewer is the READ-ONLY player for the public walkthrough-publish
	// plane (P4). It is a strict subset of walkthrough.js: no authoring UI, no
	// core WS/exec transport, no cross-frame agent control. Dependency-free (pure
	// DOM in its own isolated IIFE) and inert until window.__walkthroughViewer.create()
	// is called, so it is safe to ship in every bundle; the RolePublic allowlist
	// selects it as one of the three public members.
	{"walkthrough-viewer", nil},
	// feedback-client is the third public member (P4) — a thin stub that buffers
	// visitor feedback. Dependency-free, no dev-control surface, inert until
	// window.__feedbackClient.init() is called.
	{"feedback-client", nil},
	// public-boot is the fourth public member: the glue that reads the share
	// token from window.location, fetches /s/{token}/walkthrough.json, and starts
	// the viewer. It must load AFTER variant-engine + walkthrough-viewer (it
	// calls both at DOMContentLoaded), and it is the ONE public module that runs
	// on its own — double-gated on the RolePublic version marker and the
	// /s/{token} route so it stays inert in every dev bundle.
	{"public-boot", []string{"variant-engine", "walkthrough-viewer"}},
	{"palette", []string{"core", "utils"}},
	{"style-editor", []string{"core", "utils"}},
	// override-store injects the delta stylesheet; transform renders the
	// geometry handles, listens for design.js's palette-show, snaps drags, and
	// emits design_edit. transform depends on the store + core + utils, and
	// loads after design so the selection signal source is present.
	{"override-store", nil},
	{"transform", []string{"core", "utils", "override-store", "overlay", "design"}},
	// indicator-bridge owns the global Ctrl/Cmd+Y hotkey registration in every
	// frame and installs the minimal forwarding __devtool_indicator surface for
	// content frames. Shared role set. The full indicator (chrome-only) detects
	// the bridge and skips its own hotkey registration, then overwrites the
	// forwarding surface with the real implementation.
	{"indicator-bridge", nil},
	// The floating indicator is split into four modules sharing symbols via
	// the window.__devtool_indicator_internal namespace, in load order:
	// indicator-styles (design tokens/STYLES/ICONS) → indicator-data
	// (reactive store, data refresh, chaos client) → indicator-tabs (VanJS
	// tab components) → indicator (chrome shell: bug, panel, hotkeys,
	// capture modes). Later modules alias earlier ones at eval time; the
	// chrome shell assigns its runtime-invoked functions back onto the
	// namespace, so all four must load contiguously in this order.
	{"indicator-styles", []string{"ui-tokens"}},
	{"indicator-data", []string{"core", "utils", "indicator-styles"}},
	{"indicator-tabs", []string{"indicator-data", "indicator-styles"}},
	{"indicator", []string{"core", "utils", "sketch", "design", "style-editor", "toast", "framework-detector", "api-tracker", "shadow-root", "indicator-bridge", "indicator-styles", "indicator-data", "indicator-tabs"}},
	{"snapshot-helper", []string{"core"}},
	{"diagnostics", []string{"utils", "core"}},
	{"session", []string{"core"}},
	{"store", []string{"core"}},
	{"content", []string{"utils"}},
	{"text-fragility", []string{"utils"}},
	{"responsive-risk", []string{"utils"}},
	{"wireframe", []string{"utils"}},
	{"responsive", []string{"utils"}},
	// responsive-mode augments the window.__devtool_responsive object created by
	// responsive.js with the interactive panel API, so it must load after it.
	{"responsive-mode", []string{"responsive"}},
	{"api", []string{
		"core", "frames", "utils", "overlay", "inspection", "tree", "visual",
		"layout", "interactive", "capture", "accessibility",
		"audit-quality", "audit-api", "audit-loading", "audit-report", "interaction", "mutation",
		"voice", "indicator", "sketch", "design", "walkthrough", "palette",
		"diagnostics", "session", "store", "content",
		"wireframe", "responsive", "responsive-mode", "style-editor",
		"text-fragility", "responsive-risk", "snapshot-helper", "toast",
	}},
}

// moduleRole classifies modules for the per-frame bundle split. Modules not
// listed here are SHARED and ship in every bundle. The full (RoleFull) bundle
// always includes every module regardless of this map.
//
// A module may only be RoleContent (excluded from the chrome bundle) if
// nothing shipping in the chrome bundle dereferences its exports at bundle
// eval. api.js is the main hazard: it hard-derefs
// overlay/inspection/tree/visual/layout/interactive/capture/accessibility/
// audit(-quality, which itself eval-derefs -dom/-css/-security/-performance/
// -utils)/voice/sketch/design/style-editor/indicator inside the
// window.__devtool literal, so those all stay shared even though most of
// them only ever do real work in the content frame. The modules below are
// safe: api.js either doesn't touch them, references them as plain values
// (`mutations: mutations`), or guards them (`wireframe ? … : fallback`,
// `window.__devtool_snapshot || {…}`), and core.js pre-installs a
// __devtool_diagnostics fallback. session/palette/toast/responsive(-mode)
// stay shared deliberately: session feeds page-session tracking from every
// frame, palette + toast are user surfaces in both frames, and the indicator
// toggles window.__devtool_responsive in its own (shell) window.
//
// A module may only be RoleChrome (excluded from the content bundle) if its
// content-side callers are covered: indicator-bridge replaces the indicator's
// nested-frame hotkey forwarding + addAttachment surface, walkthrough-proxy
// replaces walkthrough's non-host forwarding proxy, and api.js guards its
// indicator block with a not-loaded fallback.
var moduleRole = map[string]Role{
	// Chrome-only: the shell UI itself.
	"indicator-styles": RoleChrome,
	"indicator-data":   RoleChrome,
	"indicator-tabs":   RoleChrome,
	"indicator":        RoleChrome,
	"walkthrough":      RoleChrome,

	// Content-only: page-operating/telemetry modules the shell never
	// eval-requires.
	"audit-api":       RoleContent,
	"audit-loading":   RoleContent,
	"interaction":     RoleContent,
	"mutation":        RoleContent,
	"override-store":  RoleContent,
	"transform":       RoleContent,
	"snapshot-helper": RoleContent,
	"diagnostics":     RoleContent,
	"store":           RoleContent,
	"content":         RoleContent,
	"text-fragility":  RoleContent,
	"responsive-risk": RoleContent,
	"wireframe":       RoleContent,
}

// rolePublicModules is the EXPLICIT ALLOWLIST for the public bundle (P4). Unlike
// moduleRole (a subtractive per-frame classification), this is the complete,
// closed set of modules permitted in RolePublic: the variant renderer, the
// read-only walkthrough viewer, the feedback client, and the boot glue —
// nothing else. The first three are dependency-free and public-boot depends only
// on two of them, so the public bundle's dependency closure is exactly these
// four; role_public_test.go pins this set (golden manifest), scans the
// assembled bundle for forbidden dev-surface tokens, and walks the closure so a
// forbidden module can never enter without failing the build.
var rolePublicModules = map[string]bool{
	"variant-engine":     true,
	"walkthrough-viewer": true,
	"feedback-client":    true,
	"public-boot":        true,
}

// includeInRole reports whether module name ships in the bundle for role.
func includeInRole(name string, role Role) bool {
	switch role {
	case RoleChrome:
		return moduleRole[name] != RoleContent
	case RoleContent:
		return moduleRole[name] != RoleChrome
	case RolePublic:
		// Allowlist, not blocklist: only the sanctioned public members ship.
		return rolePublicModules[name]
	default: // RoleFull
		return true
	}
}

// moduleScript maps module names to their embedded JS variables.
var moduleScript = map[string]string{
	"core":               coreJS,
	"frames":             framesJS,
	"html2canvas-loader": html2canvasLoaderJS,
	"authbreakout":       authBreakoutJS,
	"ui-tokens":          uiTokensJS,
	"shadow-root":        shadowRootJS,
	"framework-detector": frameworkDetectorJS,
	"api-tracker":        apiTrackerJS,
	"utils":              utilsJS,
	"overlay":            overlayJS,
	"inspection":         inspectionJS,
	"tree":               treeJS,
	"visual":             visualJS,
	"layout":             layoutJS,
	"interactive":        interactiveJS,
	"capture":            captureJS,
	"accessibility":      accessibilityJS,
	"audit-utils":        auditUtilsJS,
	"audit-report":       auditReportJS,
	"audit-dom":          auditDomJS,
	"audit-css":          auditCssJS,
	"audit-security":     auditSecurityJS,
	"audit-performance":  auditPerformanceJS,
	"audit-quality":      auditQualityJS,
	"audit-api":          auditApiJS,
	"audit-loading":      auditLoadingJS,
	"interaction":        interactionJS,
	"mutation":           mutationJS,
	"toast":              toastJS,
	"voice":              voiceJS,
	"sketch":             sketchJS,
	"design":             designJS,
	"walkthrough":        walkthroughJS,
	"variant-engine":     variantEngineJS,
	"walkthrough-viewer": walkthroughViewerJS,
	"feedback-client":    feedbackClientJS,
	"public-boot":        publicBootJS,
	"palette":            paletteJS,
	"style-editor":       styleEditorJS,
	"override-store":     overrideStoreJS,
	"transform":          transformJS,
	"indicator-bridge":   indicatorBridgeJS,
	"walkthrough-proxy":  walkthroughProxyJS,
	"indicator-styles":   indicatorStylesJS,
	"indicator-data":     indicatorDataJS,
	"indicator-tabs":     indicatorTabsJS,
	"indicator":          indicatorJS,
	"snapshot-helper":    snapshotHelperJS,
	"diagnostics":        diagnosticsJS,
	"session":            sessionJS,
	"store":              storeJS,
	"content":            contentJS,
	"text-fragility":     textFragilityJS,
	"responsive-risk":    responsiveRiskJS,
	"wireframe":          wireframeJS,
	"responsive":         responsiveJS,
	"responsive-mode":    responsiveModeJS,
	"api":                apiJS,
}

// GetCombinedScript returns all JavaScript modules combined into a single script.
// The script is wrapped in appropriate tags and ordered for correct initialization.
// The result is cached after first call. Equivalent to
// GetCombinedScriptForRole(RoleFull).
func GetCombinedScript() string {
	return GetCombinedScriptForRole(RoleFull)
}

// GetCombinedScriptForRole returns the bundle flavour for the given frame
// role (RoleFull, RoleChrome, or RoleContent), built once and cached.
func GetCombinedScriptForRole(role Role) string {
	if s, ok := combinedScripts.Load(role); ok {
		return s.(string)
	}
	built := buildCombinedScript(role)
	s, _ := combinedScripts.LoadOrStore(role, built)
	return s.(string)
}

// buildCombinedScript assembles the modules for role in the dependency order
// defined by moduleOrder, skipping modules excluded from that role's bundle.
func buildCombinedScript(role Role) string {
	var sb strings.Builder

	// Main script block
	sb.WriteString("<script>\n")

	// The public bundle (RolePublic) is a hard-allowlisted, dev-control-free
	// artifact: it must ship NEITHER the html2canvas capture library NOR the
	// window.__devtool_* version marker, both of which are dev-surface tokens the
	// forbidden-symbol scan rejects. Every other role keeps today's behaviour.
	isPublic := role == RolePublic

	// html2canvas-pro (~211KB) is NO LONGER prepended to the always-injected
	// bundle. It blocked first paint of every proxied page and parsed in every
	// frame that never captured a screenshot. It is now served on demand from
	// /__devtool_html2canvas and injected only when a capture actually runs, via
	// window.__devtool_ensureHtml2canvas (html2canvas-loader.js, shipped in every
	// non-public bundle). This mirrors how axe-core is already lazy-loaded.

	sb.WriteString("(function() {\n")
	sb.WriteString("  'use strict';\n\n")

	if isPublic {
		// Public-namespaced version marker — deliberately NOT __devtool_* so the
		// public bundle stays provably free of the dev-control namespace.
		sb.WriteString("  // Version injected at build/runtime (public plane)\n")
		sb.WriteString("  window.__agnt_public_version = '")
		sb.WriteString(Version)
		sb.WriteString("';\n\n")
	} else {
		// Inject version as first thing in the script
		sb.WriteString("  // Version injected at build/runtime\n")
		sb.WriteString("  window.__devtool_version = '")
		sb.WriteString(Version)
		sb.WriteString("';\n\n")
	}

	// Load modules in dependency order from moduleOrder
	for _, m := range moduleOrder {
		if !includeInRole(m.name, role) {
			continue
		}
		sb.WriteString("  // ")
		sb.WriteString(m.name)
		sb.WriteString(" module\n")
		sb.WriteString(wrapModule(moduleScript[m.name]))
		sb.WriteString("\n\n")
	}

	sb.WriteString("})();\n")
	sb.WriteString("</script>\n")

	return sb.String()
}

// wrapModule removes the outer IIFE from a module since we're wrapping everything
// in a single IIFE. It also indents the code for readability.
func wrapModule(js string) string {
	// Remove leading/trailing whitespace
	js = strings.TrimSpace(js)

	// Remove outer IIFE wrapper if present: (function() { ... })();
	if strings.HasPrefix(js, "(function()") {
		// Find the matching closing
		depth := 0
		start := -1
		end := -1

		for i, c := range js {
			if c == '{' {
				if start == -1 {
					start = i + 1
				}
				depth++
			} else if c == '}' {
				depth--
				if depth == 0 {
					end = i
					break
				}
			}
		}

		if start != -1 && end != -1 {
			// Extract content between braces
			content := js[start:end]
			// Remove 'use strict' if present (we add it at the top level)
			content = strings.Replace(content, "'use strict';", "", 1)
			content = strings.Replace(content, `"use strict";`, "", 1)
			return strings.TrimSpace(content)
		}
	}

	return js
}

// GetAxeCore returns the bundled axe-core JavaScript library.
func GetAxeCore() string {
	return axeCoreJS
}

// GetHtml2Canvas returns the bundled html2canvas-pro library, served on demand
// (not inlined into the always-injected bundle) from /__devtool_html2canvas.
func GetHtml2Canvas() string {
	return html2canvasProJS
}

// GetScriptNames returns the list of embedded script names for debugging.
func GetScriptNames() []string {
	names := make([]string, len(moduleOrder))
	for i, m := range moduleOrder {
		names[i] = m.name + ".js"
	}
	return names
}
