// Screenshot/video harness for the agnt browser-overlay modes.
//
// Builds a static page that embeds the exact proxy-injected __devtool bundle
// (generated by ./genbundle), serves it over http (so the metrics WebSocket
// fails async instead of throwing on file://), then drives each mode with
// Playwright's bundled Chromium and captures a PNG + a short video per mode.
//
//   go run ./docs-site/screenshots/genbundle > docs-site/screenshots/bundle.html
//   node docs-site/screenshots/capture.mjs
//
// Output: docs-site/static/img/<mode>.png and docs-site/screenshots/videos/<mode>.webm
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';

const here = path.dirname(fileURLToPath(import.meta.url));
const imgDir = path.join(here, '..', 'static', 'img');
const vidDir = path.join(here, 'videos');
const serveDir = path.join(here, '.serve');
const VIEW = {width: 1440, height: 900};

fs.mkdirSync(serveDir, {recursive: true});
fs.mkdirSync(vidDir, {recursive: true});
fs.mkdirSync(imgDir, {recursive: true});

// Build the served page: sample markup + injected bundle.
const page = fs.readFileSync(path.join(here, 'page.html'), 'utf8');
const bundle = fs.readFileSync(path.join(here, 'bundle.html'), 'utf8');
// split/join, not replace: the bundle contains `$&`/`$\`` regex literals that
// String.prototype.replace would interpret as replacement patterns.
fs.writeFileSync(path.join(serveDir, 'index.html'), page.split('<!--AGNT_BUNDLE-->').join(bundle));

// axe-core is served by the real proxy at /__devtool_axe; mirror that here so
// __devtool.auditAccessibility() works against the static harness.
const axePath = path.join(here, '..', '..', 'internal', 'proxy', 'scripts', 'axe-core.min.js');

// Mock API endpoints (delayed JSON) so the api-audit / loading-audit scenes
// have real fetch traffic for the in-page call buffer.
function mockAPI(req, res) {
  const u = new URL(req.url, 'http://x');
  const respond = (delay, body, status = 200) => setTimeout(() => {
    res.writeHead(status, {'Content-Type': 'application/json'});
    res.end(JSON.stringify(body));
  }, delay);
  // POST /api/customer: distinct server-side failure modes for the
  // debug-to-e2e scene's failure-condition e2e generation.
  if (req.method === 'POST' && u.pathname === '/api/customer') {
    let raw = '';
    req.on('data', (c) => { raw += c; });
    req.on('end', () => {
      let b = {};
      try { b = JSON.parse(raw); } catch { return respond(80, {error: 'malformed JSON body'}, 400); }
      if (b.company === 'Globex Corp') return respond(200, {error: 'company already exists', field: 'company'}, 409);
      if (b.plan === 'Enterprise' && b.seats < 25) return respond(150, {error: 'Enterprise plan requires at least 25 seats', field: 'seats'}, 422);
      if (b.company === 'Crash Test') return respond(300, {error: 'internal server error'}, 500);
      return respond(180, {id: 1042, company: b.company});
    });
    return;
  }
  if (u.pathname === '/api/users') return respond(260, {users: [1, 2, 3, 4, 5].map(i => ({id: i}))});
  if (u.pathname.startsWith('/api/user/')) return respond(140, {id: u.pathname.split('/').pop(), name: 'user'});
  if (u.pathname === '/api/config') return respond(90, {theme: 'dark', flags: {beta: true}});
  if (u.pathname === '/api/report') return respond(420, {ok: true});
  res.writeHead(404); res.end('{}');
}

// Minimal static server.
const server = http.createServer((req, res) => {
  if (req.url.startsWith('/api/')) return mockAPI(req, res);
  if (req.url.split('?')[0] === '/__devtool_axe') {
    fs.readFile(axePath, (err, buf) => {
      if (err) { res.writeHead(404); res.end('not found'); return; }
      res.writeHead(200, {'Content-Type': 'application/javascript'});
      res.end(buf);
    });
    return;
  }
  const file = path.join(serveDir, req.url === '/' ? 'index.html' : req.url.split('?')[0]);
  fs.readFile(file, (err, buf) => {
    if (err) { res.writeHead(404); res.end('not found'); return; }
    res.writeHead(200, {'Content-Type': 'text/html'});
    res.end(buf);
  });
});
await new Promise(r => server.listen(0, r));
const url = `http://localhost:${server.address().port}/index.html`;
console.log('serving', url);

const browser = await chromium.launch();

// ONLY=<scene> node capture.mjs re-captures a single scene.
const only = process.env.ONLY;

async function shot(name, drive) {
  if (only && name !== only) return;
  const ctx = await browser.newContext({viewport: VIEW, recordVideo: {dir: vidDir, size: VIEW}});
  const pg = await ctx.newPage();
  pg.on('pageerror', e => console.log(`  [${name}] pageerror:`, e.message));
  await pg.goto(url, {waitUntil: 'load'});
  await pg.waitForFunction(() => window.__devtool && typeof window.__devtool === 'object', {timeout: 15000});
  await pg.waitForTimeout(800); // let UI settle / indicator mount
  try {
    await drive(pg);
  } catch (e) {
    console.log(`  [${name}] drive error:`, e.message);
  }
  await pg.waitForTimeout(700);
  await pg.screenshot({path: path.join(imgDir, `${name}.png`)});
  const video = pg.video();
  await ctx.close(); // flushes video
  if (video) {
    const vp = await video.path();
    fs.renameSync(vp, path.join(vidDir, `${name}.webm`));
  }
  console.log('  captured', name);
}

await shot('indicator', async (pg) => {
  await pg.evaluate(() => window.__devtool.indicator.show());
  await pg.waitForTimeout(300);
  await pg.evaluate(() => window.__devtool.indicator.togglePanel());
});

await shot('sketch-mode', async (pg) => {
  await pg.evaluate(() => window.__devtool.sketch.open());
  await pg.waitForTimeout(500);
  await pg.evaluate(() => window.__devtool.sketch.setTool && window.__devtool.sketch.setTool('rectangle'));
  // draw two rectangles with the mouse
  await pg.mouse.move(620, 260); await pg.mouse.down(); await pg.mouse.move(900, 380, {steps: 12}); await pg.mouse.up();
  await pg.waitForTimeout(200);
  await pg.evaluate(() => window.__devtool.sketch.setTool && window.__devtool.sketch.setTool('arrow'));
  await pg.mouse.move(640, 460); await pg.mouse.down(); await pg.mouse.move(880, 540, {steps: 12}); await pg.mouse.up();
});

await shot('design-mode', async (pg) => {
  await pg.evaluate(() => window.__devtool.design.start());
  await pg.waitForTimeout(400);
  // try to select a card element so the design panel populates
  try { await pg.click('.card', {timeout: 1500}); } catch {}
  await pg.waitForTimeout(400);
});

await shot('responsive-mode', async (pg) => {
  await pg.evaluate(() => window.__devtool.responsive.open());
  await pg.waitForTimeout(700);
  await pg.evaluate(() => window.__devtool.responsive.setWidth(414));
  await pg.waitForTimeout(600);
});

// ---------------------------------------------------------------------------
// Audit & feature demo scenes
// ---------------------------------------------------------------------------

// NOTE: __devtool.selectElement() is not used here — its full-viewport overlay
// intercepts document.elementFromPoint, so the hover highlight never appears
// and the click never resolves (bug; also present in a real browser).
await shot('element-inspection', async (pg) => {
  const stops = ['header nav', '.cards .card:nth-child(1)', '.panel table', 'button.primary'];
  for (const sel of stops) {
    await pg.evaluate((s) => {
      const info = window.__devtool.getElementInfo(s);
      window.__devtool.highlight(s, {duration: 1300});
      window.__devtool.toast.info('<' + info.tag + '> ' + (info.classes.length ? '.' + info.classes.join('.') : info.selector));
    }, sel);
    await pg.waitForTimeout(1500);
  }
  // hold a final highlight so the last frame (the poster) shows the overlay
  await pg.evaluate(() => window.__devtool.highlight('.cards .card:nth-child(1)', {duration: 6000}));
  await pg.waitForTimeout(600);
});

await shot('layout-diagnostics', async (pg) => {
  await pg.evaluate(() => document.getElementById('layout-demo').scrollIntoView({behavior: 'smooth', block: 'center'}));
  await pg.waitForTimeout(1000);
  await pg.evaluate(() => {
    const r = window.__devtool.diagnoseLayoutIssues();
    window.__diag = r;
    const parts = Object.entries(r.by_check).filter(([, n]) => n > 0).map(([k, n]) => k + ' ×' + n);
    window.__devtool.toast.show({message: 'Layout diagnostics: ' + r.count + ' issues — ' + parts.join(', '), type: 'warning', duration: 9000});
  });
  await pg.waitForTimeout(900);
  // outline each finding: symptom in red, offending ancestor dashed amber
  await pg.evaluate(() => {
    for (const f of window.__diag.findings) {
      const el = document.querySelector(f.selector);
      if (el) { el.style.outline = '3px solid #ef4444'; el.style.outlineOffset = '2px'; }
      if (f.cause) {
        const c = document.querySelector(f.cause);
        if (c) { c.style.outline = '3px dashed #f59e0b'; c.style.outlineOffset = '4px'; }
      }
    }
  });
  await pg.waitForTimeout(1100);
});

await shot('accessibility-audit', async (pg) => {
  await pg.evaluate(() => document.getElementById('announcements').scrollIntoView({behavior: 'smooth', block: 'center'}));
  await pg.waitForTimeout(900);
  const res = await pg.evaluate(() => window.__devtool.auditAccessibility());
  await pg.evaluate((r) => {
    const s = r.stats || {};
    window.__devtool.toast.show({
      message: 'Accessibility [' + (r.grade || '?') + '] ' + (s.totalIssues ?? '?') + ' issues — ' +
        (s.critical || 0) + ' critical, ' + (s.serious || 0) + ' serious (WCAG ' + String(r.level || 'aa').toUpperCase() + ')',
      type: 'error', duration: 9000,
    });
    // outline every flagged element (raw.issuesByType[*].examples[*].selector)
    const types = (r.raw && r.raw.issuesByType) || {};
    for (const t of Object.values(types)) {
      for (const ex of t.examples || []) {
        const el = document.querySelector(ex.selector);
        if (el) { el.style.outline = '3px solid #ef4444'; el.style.outlineOffset = '2px'; }
      }
    }
  }, res);
  await pg.waitForTimeout(1400);
});

await shot('quality-audit', async (pg) => {
  await pg.evaluate(() => window.__devtool.indicator.show());
  await pg.waitForTimeout(400);
  await pg.evaluate(() => window.__devtool.indicator.togglePanel());
  await pg.waitForTimeout(700);
  await pg.locator('#__devtool-audit-btn').click();
  await pg.waitForTimeout(900);
  await pg.getByText('Full Page Audit', {exact: true}).first().click();
  await pg.waitForTimeout(3000); // audit runs; result lands in the panel as a graded attachment
});

await shot('api-audit', async (pg) => {
  // watch the calls land in the indicator's Network tab while they fire
  await pg.evaluate(() => window.__devtool.indicator.show());
  await pg.waitForTimeout(300);
  await pg.evaluate(() => window.__devtool.indicator.togglePanel());
  await pg.waitForTimeout(500);
  try { await pg.locator('[title="Network requests"]').click({timeout: 2000}); } catch {}
  // serial waterfall + N+1 fan-out + duplicate calls against the mock API
  await pg.evaluate(async () => {
    await fetch('/api/users').then((r) => r.json());
    for (let i = 1; i <= 5; i++) await fetch('/api/user/' + i).then((r) => r.json());
    await fetch('/api/config');
    await fetch('/api/config');
  });
  await pg.waitForTimeout(500);
  await pg.evaluate(() => {
    const r = window.__devtool_audit_api.auditAPIEfficiency();
    window.__devtool.toast.show({message: 'API audit [' + r.grade + '] ' + r.summary, type: 'warning', duration: 9000});
  });
  await pg.waitForTimeout(1400);
});

await shot('loading-audit', async (pg) => {
  await pg.evaluate(() => document.getElementById('reports-panel').scrollIntoView({behavior: 'smooth', block: 'center'}));
  await pg.waitForTimeout(800);
  await pg.evaluate(() => window.__demoLoadingCascade()); // ~2.3s animated spinner cascade
  await pg.waitForTimeout(400);
  await pg.evaluate(() => {
    const r = window.__devtool_audit_loading.auditLoading();
    window.__devtool.toast.show({message: 'Loading-UX audit [' + r.grade + '] ' + r.summary, type: 'warning', duration: 9000});
  });
  await pg.waitForTimeout(1400);
});

await shot('color-palette', async (pg) => {
  await pg.evaluate(() => window.__devtool.diagnostics.showColorPalette());
  await pg.waitForTimeout(1800);
  await pg.evaluate(() => { window.__devtool.diagnostics.clearAll(); window.__devtool.diagnostics.showTypographyPanel(); });
  await pg.waitForTimeout(1600);
});

// This scene shows the responsive checks through responsive mode's width sweep,
// where the invoices table visibly breaks at phone widths.
await shot('responsive-audit', async (pg) => {
  await pg.evaluate(() => window.__devtool.responsive.open());
  await pg.waitForTimeout(800);
  for (const w of [1024, 768, 375]) {
    await pg.evaluate((width) => window.__devtool.responsive.setWidth(width), w);
    await pg.waitForTimeout(1300);
  }
  await pg.waitForTimeout(500);
});

// Full debug-to-e2e workflow in one take: the audit tools diagnose a thorny
// CSS issue (fixed note trapped by a transform containing block, clipped
// dropdown, dead z-index), the diagnosis is encoded as a site-wide regression
// check that goes red → fix → green, then every failure condition of the
// dynamic "Add customer" form is driven end to end as generated e2e cases.
await shot('debug-to-e2e', async (pg) => {
  const toast = (message, type = 'info', duration = 4200) =>
    pg.evaluate((t) => window.__devtool.toast.show(t), {message, type, duration});

  // --- Phase 1: diagnose the CSS issue with the audit tools ---
  await pg.evaluate(() => window.__devtool.indicator.show());
  await toast('Bug report: "standup note swallows clicks & the export menu is cut off"', 'error');
  await pg.evaluate(() => document.getElementById('layout-demo').scrollIntoView({behavior: 'smooth', block: 'center'}));
  await pg.waitForTimeout(1600);
  await pg.evaluate(() => {
    const r = window.__devtool.diagnoseLayoutIssues();
    window.__diag = r;
    const parts = Object.entries(r.by_check).filter(([, n]) => n > 0).map(([k, n]) => k + ' ×' + n);
    window.__devtool.toast.show({message: 'diagnoseLayoutIssues(): ' + r.count + ' issues — ' + parts.join(', '), type: 'warning', duration: 5000});
    for (const f of r.findings) {
      const el = document.querySelector(f.selector);
      if (el) { el.style.outline = '3px solid #ef4444'; el.style.outlineOffset = '2px'; }
      if (f.cause) {
        const c = document.querySelector(f.cause);
        if (c) { c.style.outline = '3px dashed #f59e0b'; c.style.outlineOffset = '4px'; }
      }
    }
  });
  await pg.waitForTimeout(2400);
  await pg.evaluate(() => {
    const trap = (window.__diag.findings || []).find((f) => f.fix) || {};
    window.__devtool.toast.show({message: 'Root cause: ' + (trap.detail || 'containing-block trap') + ' — fix: ' + (trap.fix || 'remove the transform'), type: 'info', duration: 5600});
  });
  await pg.waitForTimeout(2800);
  await pg.evaluate(() => {
    const r = window.__devtool_audit_css.auditCSS({detailLevel: 'summary'});
    window.__devtool.toast.show({message: 'CSS audit [' + r.grade + '] ' + r.summary, type: 'warning', duration: 4600});
  });
  await pg.waitForTimeout(2600);

  // --- Phase 2: site-wide regression check — red, fix, green ---
  await toast('Encoding diagnosis as a site-wide regression check…');
  await pg.waitForTimeout(1800);
  await pg.evaluate(() => {
    const r = window.__devtool.diagnoseLayoutIssues();
    window.__devtool.toast.show({message: 'Regression check: FAIL — ' + r.count + ' layout violations across the page', type: 'error', duration: 4200});
  });
  await pg.waitForTimeout(2400);
  await toast('Applying fix: drop translateZ(0) hack, un-clip export card, position the filters', 'info');
  await pg.evaluate(() => {
    document.querySelector('.activity-wrap').style.transform = 'none';
    document.getElementById('activity-card').style.overflow = 'visible';
    document.querySelector('.filters').style.position = 'relative';
    for (const el of document.querySelectorAll('#layout-demo *, .pinned-note')) {
      el.style.outline = ''; el.style.outlineOffset = '';
    }
  });
  await pg.waitForTimeout(1800);
  await pg.evaluate(() => {
    const r = window.__devtool.diagnoseLayoutIssues();
    const ok = r.count === 0;
    window.__devtool.toast.show({
      message: ok ? 'Regression check: PASS — 0 violations · snapshot baseline saved for CI compare'
                  : 'Regression check: ' + r.count + ' violations remaining',
      type: ok ? 'success' : 'warning', duration: 4800,
    });
  });
  await pg.waitForTimeout(2600);

  // --- Phase 3: generate e2e tests for every failure condition of the form ---
  await pg.evaluate(() => document.getElementById('customer-form').scrollIntoView({behavior: 'smooth', block: 'center'}));
  await toast('Generating e2e tests for every failure condition of the Add-customer form…');
  await pg.waitForTimeout(2000);

  const cases = [
    {name: 'baseline-valid', company: 'Initrode', email: 'ops@initrode.com', seats: '25', expect: '201-style success'},
    {name: 'empty-required-fields', company: '', email: '', seats: '', expect: '3 client validation errors'},
    {name: 'invalid-email', company: 'Initrode', email: 'not-an-email', seats: '25', expect: 'email validation error'},
    {name: 'seats-out-of-range', company: 'Initrode', email: 'ops@initrode.com', seats: '0', expect: 'range validation error'},
    {name: 'duplicate-company', company: 'Globex Corp', email: 'ops@globex.com', seats: '25', expect: 'HTTP 409 conflict'},
    {name: 'plan-seat-constraint', company: 'Initrode', email: 'ops@initrode.com', seats: '5', plan: 'Enterprise', expect: 'HTTP 422 rule violation'},
    {name: 'server-error', company: 'Crash Test', email: 'ops@crash.dev', seats: '25', expect: 'HTTP 500 surfaced to user'},
  ];
  let n = 0;
  for (const c of cases) {
    await pg.evaluate(() => window.__demoFormReset());
    if (c.company) { await pg.click('#f-company'); await pg.type('#f-company', c.company, {delay: 18}); }
    if (c.email) { await pg.click('#f-email'); await pg.type('#f-email', c.email, {delay: 14}); }
    if (c.seats) { await pg.click('#f-seats'); await pg.type('#f-seats', c.seats, {delay: 30}); }
    if (c.plan) await pg.selectOption('#f-plan', c.plan);
    await pg.click('#f-submit');
    await pg.waitForTimeout(700);
    const observed = await pg.evaluate(() => {
      const l = window.__formLast || {};
      if (l.stage === 'client-validation') return Object.keys(l.errors).length + ' field errors';
      if (l.stage === 'server') return 'HTTP ' + l.status;
      return l.stage || 'no result';
    });
    n++;
    const pass = c.name === 'baseline-valid';
    await toast('e2e ' + n + '/' + cases.length + ' [' + c.name + '] expect ' + c.expect + ' — observed ' + observed + ' ✓', pass ? 'success' : 'warning', 3000);
    await pg.waitForTimeout(1500);
  }
  await toast('replaytest: 6 failure-condition e2e tests + 1 passing baseline generated', 'success', 6000);
  await pg.waitForTimeout(2200);
});

await browser.close();
server.close();
console.log('done');
